name: Deploy to Heroku

on:
  workflow_run:
    workflows: ["Django CI/CD Pipeline"]
    branches: [main]
    types:
      - completed

jobs:
  deploy-heroku:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

      - name: Run Heroku migrations
        run: |
          # Install Heroku CLI
          curl https://cli-assets.heroku.com/install.sh | sh

          # Login to Heroku
          echo ${{ secrets.HEROKU_API_KEY }} | heroku auth:token

          # Run migrations in correct order
          heroku run python manage.py migrate contenttypes --app ${{ secrets.HEROKU_APP_NAME }}
          heroku run python manage.py migrate auth --app ${{ secrets.HEROKU_APP_NAME }}
          heroku run python manage.py migrate accounts --app ${{ secrets.HEROKU_APP_NAME }}
          heroku run python manage.py migrate --app ${{ secrets.HEROKU_APP_NAME }}

          # Collect static files
          heroku run python manage.py collectstatic --noinput --app ${{ secrets.HEROKU_APP_NAME }}

      - name: Verify Heroku deployment
        run: |
          echo "🔍 Verifying Heroku deployment..."
          # Add health check
          # curl -f https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/health/ || exit 1
          echo "Heroku deployment verification placeholder"
