name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Django CI/CD"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          # Sync files to server
          rsync -avz --delete \
            --exclude='.git' \
            --exclude='__pycache__' \
            --exclude='*.pyc' \
            --exclude='.env' \
            --exclude='node_modules' \
            . ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_PATH }}

      - name: Run deployment commands on server
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd ${{ secrets.VPS_PATH }}
            
            # Activate virtual environment
            source venv/bin/activate
            
            # Install/update dependencies
            pip install -r requirements.txt
            
            # Create static directory if it doesn't exist
            mkdir -p static
            
            # Run migrations in correct order
            python manage.py migrate contenttypes
            python manage.py migrate auth
            python manage.py migrate accounts
            python manage.py migrate
            
            # Collect static files
            python manage.py collectstatic --noinput
            
            # Restart services
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
            
            # Optional: restart celery if using
            # sudo systemctl restart celery
          EOF
